name: "godot-ci export"
on:
  push:
    branches:
      - "main"

env:
  EXPORT_NAME: snald

jobs:
  export:
    strategy:
      fail-fast: true
      matrix:
        target: [windows, mac, linux]
    name: Matrix Export
    runs-on: ubuntu-latest
    steps:
      - name: Cache Godot stuff
        id: cache_godot
        uses: actions/cache@v3
        with:
          path: ~/.local/*godot*
          key: ${{ matrix.target }}-godot-things
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          SNALD_TARGET=${{ matrix.target }} TYPE=linux_headless.64 ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}
          path: build/${{ matrix.target }}

  itch-rolling:
    name: Upload to itch.io
    runs-on: ubuntu-latest
    needs: [export]
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - mac
          - linux
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: ${{ matrix.channel }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./build/${{ matrix.channel }}
          itchUsername: handlewithcaregames
          itchGameId: snald
          buildChannel: ${{ matrix.channel }}-rolling
