name: "godot-ci export"
on:
  push:

jobs:
  build:
    name: Build all versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hwcgames/snald/.github/workflows/build.yml@main

  itch-rolling:
    name: Upload to itch.io
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - macos
          - linux
    steps:
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./build/${{ matrix.channel }}
          itchUsername: hwcgames
          itchGameId: snald
          buildChannel: ${{ matrix.channel }}-rolling
