name: "godot-ci export"
on:
  push:
    tags:
      - "*"

env:
  GODOT_VERSION: 3.4.1
  EXPORT_NAME: snald

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
          mkdir -p build/windows/maps
          cp -r maps/*.map build/windows/maps
          cp -r addons/qodot/bin/win64/* LICENSE ATTRIBUTION build/windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
          mkdir -p build/linux/maps
          cp -r maps/*.map build/linux/maps
          cp -r addons/qodot/bin/x11/* LICENSE ATTRIBUTION build/linux
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
          mkdir -p build/mac/maps
          cp -r maps/*.map build/mac/maps
          cp -r addons/qodot/bin/osx/* LICENSE ATTRIBUTION build/mac
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: build/mac

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          SNALD_TARGET=Web ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Web
          path: build/Web


  itch-stable:
    name: Upload to itch.io
    runs-on: ubuntu-latest
    needs: [export-windows, export-linux, export-mac, export-web]
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - mac
          - linux
          - Web
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: ${{ matrix.channel }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./build/${{ matrix.channel }}
          itchUsername: handlewithcaregames
          itchGameId: snald
          buildChannel: ${{ matrix.channel }}-tagged
          buildNumber: ${{ github.ref_name }}
