name: "godot-ci export"
on:
  push:
    tags:
      - "*"

env:
  EXPORT_NAME: snald

jobs:
  export:
    strategy:
      fail-fast: true
      matrix:
        target: [windows, mac, linux]
    name: Matrix Export
    runs-on: ubuntu-latest
    steps:
      - name: Cache Godot templates
        id: cache_godot_templates
        uses: actions/cache@v3
        with:
          path: ~/.local/share/godot
          key: ${{ matrix.target }}-godot-templates
      - name: Cache Godot binaries
        id: cache_godot_binaries
        uses: actions/cache@v3
        with:
          path: ~/.local/bin
          key: ${{ matrix.target }}-godot-binaries
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          SNALD_TARGET=${{ matrix.target }} TYPE=linux_headless.64 ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}
          path: build/${{ matrix.target }}

  itch-stable:
    name: Upload to itch.io
    runs-on: ubuntu-latest
    needs: [export]
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - mac
          - linux
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: ${{ matrix.channel }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./build/${{ matrix.channel }}
          itchUsername: handlewithcaregames
          itchGameId: snald
          buildChannel: ${{ matrix.channel }}-tagged
          buildNumber: ${{ github.ref_name }}
  github-stable:
    name: Upload to Github
    runs-on: ubuntu-latest
    needs: [export]
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: linux
          path: build/linux
      - uses: actions/download-artifact@v2.0.8
        with:
          name: mac
          path: build/mac
      - uses: actions/download-artifact@v2.0.8
        with:
          name: windows
          path: build/windows
      - name: "Create zips"
        run: |
          cd build
          zip -r9 windows.zip windows
          zip -r9 mac.zip mac
          zip -r9 linux.zip linux
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows.zip,build/mac.zip,build/linux.zip"
          body: "This is an automatically generated release build, but it is uploaded from the same job as the itch.io tagged releases, so it should be identical."
